services:
  web:
    container_name: hades-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
#     target: build
#     target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app

